/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author jarv
 */
public class PanelOutOfFriendZone extends javax.swing.JPanel {

    /**
     * Creates new form PanelOutOfFriendZone
     */
    public PanelOutOfFriendZone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuestion = new javax.swing.JPanel();
        labelQuestion = new javax.swing.JLabel();
        panelAnswer = new javax.swing.JPanel();
        panelButtonNo = new javax.swing.JPanel();
        buttonNo = new javax.swing.JButton();
        panelButtonYes = new javax.swing.JPanel();
        buttonYes = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));

        labelQuestion.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelQuestion.setText("¿QUIERES DER MI NOVIA?");
        panelQuestion.add(labelQuestion);

        add(panelQuestion, java.awt.BorderLayout.NORTH);

        panelAnswer.setLayout(new java.awt.GridLayout(1, 2));

        panelButtonNo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonNo.setText("No");
        buttonNo.setName("buttonNo"); // NOI18N
        panelButtonNo.add(buttonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 5, -1, -1));

        panelAnswer.add(panelButtonNo);

        panelButtonYes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonYes.setText("Yes");
        buttonYes.setName("buttonYes"); // NOI18N
        panelButtonYes.add(buttonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 5, -1, -1));

        panelAnswer.add(panelButtonYes);

        add(panelAnswer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNo;
    private javax.swing.JButton buttonYes;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JPanel panelAnswer;
    private javax.swing.JPanel panelButtonNo;
    private javax.swing.JPanel panelButtonYes;
    private javax.swing.JPanel panelQuestion;
    // End of variables declaration//GEN-END:variables
    
    /**
     * @return the buttonNo
     */
    public javax.swing.JButton getButtonNo() {
        return buttonNo;
    }

    /**
     * @return the buttonYes
     */
    public javax.swing.JButton getButtonYes() {
        return buttonYes;
    }

    /**
     * @return the panelButtonNo
     */
    public javax.swing.JPanel getPanelButtonNo() {
        return panelButtonNo;
    }

    /**
     * @return the panelButtonYes
     */
    public javax.swing.JPanel getPanelButtonYes() {
        return panelButtonYes;
    }
}
